languageCode = "en"
languageName = "English"
weight = 1
title = "El Khalidi"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/10364533.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Data Science Portfolio Website"
  copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "El Khalidi"
  image = "img/author.jpg"
  headline = "I'm interested in everything tech"
  bio = "Data scientist by day, programming enthusiast by night. Rocking the world of data science with a passion for programming languages and innovative technologies. You'll often find me immersed in the world of Python, crafting predictive models and uncovering insights from data. When I'm not crunching numbers, I'm diving into the depths of C++ and exploring the intricacies of game mechanics."
  links = [
    { email = "mailto:e.khalidi@outlook.com" },
#     { link = "https://link-to-some-website.com/" },
    { github = "https://github.com/emkhalidi" },
#     { gitlab = "https://gitlab.com/username" },
    { linkedin = "https://www.linkedin.com/in/el-khalidi/" },
  ]
